# Copyright 1999-2026 Gentoo Authors
# Distributed under the terms of the GNU General Public License v2

EAPI=8

# ebuild generated by hackport 0.9.1.0.9999

CABAL_HACKAGE_REVISION=5

CABAL_FEATURES="lib profile haddock hoogle hscolour"
inherit haskell-cabal

DESCRIPTION="Generically newtype to use with DerivingVia"
HOMEPAGE="https://hackage.haskell.org/package/generically"

LICENSE="BSD"
SLOT="0/${PV}"
KEYWORDS="~amd64 ~arm64 ~ppc64 ~riscv ~x86"

RDEPEND=">=dev-lang/ghc-9.0.2:=
	>=dev-haskell/base-orphans-0.8.8:=[profile?] <dev-haskell/base-orphans-0.10
"

DEPEND="${RDEPEND}
	>=dev-haskell/cabal-3.4.1.0
"

src_prepare() {
	default

	cabal_chdeps \
		'base >=4.9 && <4.18' 'base >=4.10 && <6'

	cabal-mksetup
}
