# Copyright 1999-2026 Gentoo Authors
# Distributed under the terms of the GNU General Public License v2

EAPI=8

# ebuild generated by hackport 0.9.1.0.9999

CABAL_FEATURES="lib profile haddock hoogle hscolour"
inherit haskell-cabal

DESCRIPTION="A Prelude for Polysemy – Base Reexports"
HOMEPAGE="https://github.com/tek/incipit-core#readme"

LICENSE=""	# FIXME: license unknown to cabal. Please pick it manually.
SLOT="0/${PV}"
KEYWORDS="~amd64"

RDEPEND=">=dev-haskell/data-default-0.2:=[profile?] <dev-haskell/data-default-0.9:=[profile?]
	>=dev-haskell/text-1.2.5.0:=[profile?] <dev-haskell/text-2.2:=[profile?]
	>=dev-lang/ghc-9.2.5:=
"
DEPEND="${RDEPEND}
	>=dev-haskell/cabal-2.2
"
