# Copyright 1999-2024 Gentoo Authors
# Distributed under the terms of the GNU General Public License v2

EAPI=8

# ebuild generated by hackport 0.8.4.0.9999

CABAL_HACKAGE_REVISION=7

CABAL_FEATURES="lib profile haddock hoogle hscolour"
inherit haskell-cabal

DESCRIPTION="Versatile logging framework"
HOMEPAGE="https://github.com/haskell-hvr/hslogger/wiki"
#SRC_URI="https://github.com/haskell-hvr/hslogger/archive/refs/tags/v${PV}.tar.gz -> ${P}.tar.gz"

LICENSE="BSD"
SLOT="0/${PV}"
KEYWORDS="~amd64"
IUSE="+network--gt-3-0-0"

RDEPEND=">=dev-haskell/old-locale-1.0:=[profile?] <dev-haskell/old-locale-1.1:=[profile?]
	>=dev-lang/ghc-8.8.1:=
	network--gt-3-0-0? ( >=dev-haskell/network-3.0:=[profile?] <dev-haskell/network-3.2:=[profile?]
				>=dev-haskell/network-bsd-2.8.1:=[profile?] <dev-haskell/network-bsd-2.9:=[profile?] )
	!network--gt-3-0-0? ( >=dev-haskell/network-2.6:=[profile?] <dev-haskell/network-2.9:=[profile?] )
"
DEPEND="${RDEPEND}
	>=dev-haskell/cabal-3.0.0.0
"

src_configure() {
	haskell-cabal_src_configure \
		$(cabal_flag network--gt-3-0-0 network--gt-3_0_0)
}
