# Copyright 1999-2026 Gentoo Authors
# Distributed under the terms of the GNU General Public License v2

EAPI=8

# ebuild generated by hackport 0.9.1.0.9999

CABAL_FEATURES="lib profile haddock hoogle hscolour"
inherit haskell-cabal

DESCRIPTION="A Haskell implementation of the DBusMenu protocol"
HOMEPAGE="https://github.com/taffybar/dbus-menu#readme"

LICENSE="BSD"
SLOT="0/${PV}"
KEYWORDS="~amd64"

RDEPEND=">=dev-haskell/dbus-1:=[profile?] <dev-haskell/dbus-2:=[profile?]
	>=dev-haskell/enclosed-exceptions-1.0.0.1:=[profile?] <dev-haskell/enclosed-exceptions-1.1:=[profile?]
	>=dev-haskell/gi-glib-2.0:=[profile?] <dev-haskell/gi-glib-2.1:=[profile?]
	>=dev-haskell/gi-gobject-2.0:=[profile?] <dev-haskell/gi-gobject-2.1:=[profile?]
	>=dev-haskell/gi-gtk3-3.0:=[profile?] <dev-haskell/gi-gtk3-3.1:=[profile?]
	>=dev-haskell/haskell-gi-0.21.2:=[profile?] <dev-haskell/haskell-gi-0.27:=[profile?]
	>=dev-haskell/haskell-gi-base-0.21.1:=[profile?] <dev-haskell/haskell-gi-base-0.27:=[profile?]
	>=dev-haskell/hslogger-1.2:=[profile?] <dev-haskell/hslogger-1.4:=[profile?]
	>=dev-haskell/text-1.2:=[profile?] <dev-haskell/text-2.2:=[profile?]
	>=dev-lang/ghc-9.0.2:=
	x11-libs/gtk+:3
"
DEPEND="${RDEPEND}
	>=dev-haskell/cabal-3.4.1.0
	virtual/pkgconfig
"
