# Copyright 1999-2026 Gentoo Authors
# Distributed under the terms of the GNU General Public License v2

EAPI=8

# ebuild generated by hackport 0.9.1.0.9999

CABAL_FEATURES="lib profile haddock hoogle hscolour"
inherit haskell-cabal

DESCRIPTION="SOCKS Protocol Version 5"
HOMEPAGE="https://github.com/mpilgrem/crypton-socks"

LICENSE="BSD"
SLOT="0/${PV}"
KEYWORDS="~amd64"
IUSE="example +network-3-0-0-0"

RDEPEND=">=dev-haskell/cereal-0.3.1:=[profile?]
	>=dev-lang/ghc-9.0.2:=
	example? ( network-3-0-0-0? ( >=dev-haskell/network-3.0.0.0:=[profile?]
					dev-haskell/network-bsd:=[profile?] ) )
	!example? ( >=dev-haskell/network-2.6:=[profile?] )
	!network-3-0-0-0? ( >=dev-haskell/network-2.6:=[profile?] )
"
DEPEND="${RDEPEND}
	>=dev-haskell/cabal-3.4.1.0
"

src_configure() {
	haskell-cabal_src_configure \
		$(cabal_flag example example) \
		$(cabal_flag network-3-0-0-0 network-3-0-0-0)
}
