# Copyright 1999-2026 Gentoo Authors
# Distributed under the terms of the GNU General Public License v2

EAPI=8

# ebuild generated by hackport 0.9.1.0.9999

CABAL_HACKAGE_REVISION=1

CABAL_FEATURES="lib profile haddock hoogle hscolour test-suite"
inherit haskell-cabal

DESCRIPTION="A fast, light-weight web server for WAI applications"
HOMEPAGE="https://github.com/yesodweb/wai"

LICENSE="MIT"
SLOT="0/${PV}"
KEYWORDS="~amd64"
IUSE="+allow-sendfilefd debug +include-warp-version network-bytestring +x509"

RDEPEND=">=dev-haskell/async-2:=[profile?]
	>=dev-haskell/auto-update-0.2.2:=[profile?] <dev-haskell/auto-update-0.3:=[profile?]
	<dev-haskell/bsb-http-chunked-0.1:=[profile?]
	>=dev-haskell/case-insensitive-0.2:=[profile?]
	dev-haskell/hashable:=[profile?]
	dev-haskell/http-date:=[profile?]
	>=dev-haskell/http-types-0.12:=[profile?]
	>=dev-haskell/http2-5.4:=[profile?] <dev-haskell/http2-5.5:=[profile?]
	>=dev-haskell/iproute-1.3.1:=[profile?]
	>=dev-haskell/recv-0.1.0:=[profile?] <dev-haskell/recv-0.2.0:=[profile?]
	>=dev-haskell/simple-sendfile-0.2.7:=[profile?] <dev-haskell/simple-sendfile-0.3:=[profile?]
	>=dev-haskell/streaming-commons-0.1.10:=[profile?]
	dev-haskell/text:=[profile?]
	>=dev-haskell/vault-0.3:=[profile?]
	>=dev-haskell/wai-3.2.4:=[profile?] <dev-haskell/wai-3.3:=[profile?]
	dev-haskell/word8:=[profile?]
	>=dev-lang/ghc-9.0.2:=
	|| ( ( >=dev-haskell/time-manager-0.2:=[profile?] <dev-haskell/time-manager-0.3:=[profile?] )
		( >=dev-haskell/time-manager-0.3.1:=[profile?] <dev-haskell/time-manager-0.4:=[profile?] ) )
	network-bytestring? ( >=dev-haskell/network-2.2.1.5:=[profile?] <dev-haskell/network-2.2.3:=[profile?]
				>=dev-haskell/network-bytestring-0.1.3:=[profile?] <dev-haskell/network-bytestring-0.1.4:=[profile?] )
	!network-bytestring? ( >=dev-haskell/network-2.3:=[profile?] )
	x509? ( dev-haskell/crypton-x509:=[profile?] )
"
DEPEND="${RDEPEND}
	>=dev-haskell/cabal-3.4.1.0
	test? ( >=dev-haskell/hspec-1.3
		dev-haskell/http-client
		dev-haskell/quickcheck
		dev-haskell/time-manager )
"

src_configure() {
	haskell-cabal_src_configure \
		$(cabal_flag allow-sendfilefd allow-sendfilefd) \
		$(cabal_flag include-warp-version include-warp-version) \
		$(cabal_flag network-bytestring network-bytestring) \
		$(cabal_flag debug warp-debug) \
		$(cabal_flag x509 x509)
}
