# Copyright 1999-2026 Gentoo Authors
# Distributed under the terms of the GNU General Public License v2

EAPI=8

# ebuild generated by hackport 0.9.1.0.9999

CABAL_FEATURES="lib profile haddock hoogle hscolour test-suite"
inherit haskell-cabal

DESCRIPTION="A native HTTP2 client library"
HOMEPAGE="https://github.com/lucasdicioccio/http2-client"

LICENSE="BSD"
SLOT="0/${PV}"
KEYWORDS="~amd64"

RDEPEND=">=dev-haskell/async-2.1:=[profile?] <dev-haskell/async-2.3:=[profile?]
	>=dev-haskell/http2-4.1:=[profile?] <dev-haskell/http2-6:=[profile?]
	>=dev-haskell/lifted-async-0.10:=[profile?] <dev-haskell/lifted-async-0.11:=[profile?]
	>=dev-haskell/lifted-base-0.2:=[profile?] <dev-haskell/lifted-base-0.3:=[profile?]
	>=dev-haskell/network-2.6:=[profile?] <dev-haskell/network-3.2:=[profile?]
	>=dev-haskell/tls-1.8.0:=[profile?] <dev-haskell/tls-2.0.3:=[profile?]
	>=dev-haskell/transformers-base-0.4:=[profile?] <dev-haskell/transformers-base-0.5:=[profile?]
	>=dev-lang/ghc-9.2.4:=
"
DEPEND="${RDEPEND}
	>=dev-haskell/cabal-3.6.3.0
"
