# Copyright 1999-2026 Gentoo Authors
# Distributed under the terms of the GNU General Public License v2

EAPI=8

# ebuild generated by hackport 0.9.1.0.9999

CABAL_FEATURES="lib profile haddock hoogle hscolour test-suite"
inherit haskell-cabal

DESCRIPTION="X509 reader and writer"
HOMEPAGE="https://github.com/kazu-yamamoto/crypton-certificate"

LICENSE="BSD"
SLOT="0/${PV}"
KEYWORDS="~amd64"

RDEPEND=">=dev-haskell/crypton-1.1:=[profile?] <dev-haskell/crypton-1.2:=[profile?]
	>=dev-haskell/crypton-asn1-encoding-0.10.0:=[profile?] <dev-haskell/crypton-asn1-encoding-0.11:=[profile?]
	>=dev-haskell/crypton-asn1-parse-0.10.0:=[profile?] <dev-haskell/crypton-asn1-parse-0.11:=[profile?]
	>=dev-haskell/crypton-asn1-types-0.4.1:=[profile?] <dev-haskell/crypton-asn1-types-0.5:=[profile?]
	>=dev-haskell/crypton-pem-0.2.4:=[profile?] <dev-haskell/crypton-pem-0.4:=[profile?]
	dev-haskell/ram:=[profile?]
	dev-haskell/time-hourglass:=[profile?]
	>=dev-lang/ghc-9.0.2:=
"
DEPEND="${RDEPEND}
	>=dev-haskell/cabal-3.4.1.0
	test? ( dev-haskell/tasty
		dev-haskell/tasty-quickcheck )
"
