# Copyright 1999-2026 Gentoo Authors
# Distributed under the terms of the GNU General Public License v2

EAPI=8

# ebuild generated by hackport 0.9.1.0.9999

CABAL_FEATURES="lib profile haddock hoogle hscolour"
inherit haskell-cabal

DESCRIPTION="Expose a dbus server to control hslogger"
HOMEPAGE="https://github.com/IvanMalison/dbus-hslogger#readme"

LICENSE="BSD"
SLOT="0/${PV}"
KEYWORDS="~amd64"

RDEPEND=">=dev-haskell/dbus-1.0.1:=[profile?] <dev-haskell/dbus-2:=[profile?]
	>=dev-haskell/hslogger-1.2:=[profile?] <dev-haskell/hslogger-2:=[profile?]
	>=dev-haskell/optparse-applicative-0.14:=[profile?] <dev-haskell/optparse-applicative-1:=[profile?]
	>=dev-lang/ghc-9.0.2:=
"
DEPEND="${RDEPEND}
	>=dev-haskell/cabal-3.4.1.0
"
