# Copyright 1999-2026 Gentoo Authors
# Distributed under the terms of the GNU General Public License v2

EAPI=8

# ebuild generated by hackport 0.8.5.1.9999

CABAL_FEATURES=""
inherit haskell-cabal git-r3

DESCRIPTION=""
HOMEPAGE="https://hackage.haskell.org/package/bybit"

HOMEPAGE="https://github.com/Miezhiko/bb"
EGIT_REPO_URI="https://github.com/Miezhiko/bb.git"

LICENSE="LGPLv2"
SLOT="0"
KEYWORDS="~amd64"

RDEPEND="dev-haskell/aeson:=
	dev-haskell/base-unicode-symbols:=
	dev-haskell/brick:=
	dev-haskell/lens:=
	dev-haskell/network:=
	dev-haskell/text:=
	dev-haskell/vty:=
	dev-haskell/vty-crossplatform:=
	dev-haskell/websockets:=
	dev-haskell/wuss:=
	dev-haskell/yaml:=
	>=dev-lang/ghc-9.0.2:=
"
DEPEND="${RDEPEND}
	>=dev-haskell/cabal-3.4.1.0
"

S="${WORKDIR}/${P}"

src_configure() {
	cabal-mksetup
	haskell-cabal_src_configure
}
