# Copyright 1999-2026 Gentoo Authors
# Distributed under the terms of the GNU General Public License v2

EAPI=8

# ebuild generated by hackport 0.9.1.0.9999

CABAL_FEATURES="lib profile haddock hoogle hscolour test-suite"
inherit haskell-cabal

DESCRIPTION="A wrapper over the StatusNotifierItem/libappindicator dbus specification"
HOMEPAGE="https://github.com/taffybar/status-notifier-item#readme"

LICENSE="BSD"
SLOT="0/${PV}"
KEYWORDS="~amd64"

RDEPEND="<dev-haskell/byte-order-0.2:=[profile?]
	<dev-haskell/bytestring-to-vector-0.4:=[profile?]
	>=dev-haskell/dbus-1.2.1:=[profile?] <dev-haskell/dbus-2:=[profile?]
	>=dev-haskell/dbus-hslogger-0.1.0.1:=[profile?] <dev-haskell/dbus-hslogger-0.2:=[profile?]
	<dev-haskell/hslogger-1.4:=[profile?]
	<dev-haskell/lens-5.4:=[profile?]
	<dev-haskell/optparse-applicative-0.20:=[profile?]
	<dev-haskell/text-2.2:=[profile?]
	<dev-haskell/vector-0.14:=[profile?]
	>=dev-lang/ghc-9.0.2:=
"
DEPEND="${RDEPEND}
	>=dev-haskell/cabal-3.4.1.0
	test? ( <dev-haskell/hspec-3 )
"
