# Copyright 1999-2026 Gentoo Authors
# Distributed under the terms of the GNU General Public License v2

EAPI=8

# ebuild generated by hackport 0.9.1.0.9999

CABAL_FEATURES="lib profile haddock hoogle hscolour test-suite"
inherit haskell-cabal

DESCRIPTION="HTTP/2 library"
HOMEPAGE="https://github.com/kazu-yamamoto/http2"

LICENSE="BSD"
SLOT="0/${PV}"
KEYWORDS="~amd64"
IUSE="devel h2spec"

RDEPEND=">=dev-haskell/async-2.2:=[profile?] <dev-haskell/async-2.3:=[profile?]
	>=dev-haskell/case-insensitive-1.2:=[profile?] <dev-haskell/case-insensitive-1.3:=[profile?]
	>=dev-haskell/http-semantics-0.4:=[profile?] <dev-haskell/http-semantics-0.5:=[profile?]
	>=dev-haskell/http-types-0.12:=[profile?] <dev-haskell/http-types-0.13:=[profile?]
	>=dev-haskell/iproute-1.7:=[profile?] <dev-haskell/iproute-1.8:=[profile?]
	>=dev-haskell/network-3.1:=[profile?]
	>=dev-haskell/network-byte-order-0.1.7:=[profile?] <dev-haskell/network-byte-order-0.2:=[profile?]
	>=dev-haskell/network-control-0.1:=[profile?] <dev-haskell/network-control-0.2:=[profile?]
	>=dev-haskell/time-manager-0.2.3:=[profile?] <dev-haskell/time-manager-0.4:=[profile?]
	>=dev-haskell/unix-time-0.4.11:=[profile?] <dev-haskell/unix-time-0.5:=[profile?]
	>=dev-haskell/utf8-string-1.0:=[profile?] <dev-haskell/utf8-string-1.1:=[profile?]
	>=dev-lang/ghc-9.0.2:=
	devel? ( >=dev-haskell/aeson-2:=[profile?]
			dev-haskell/aeson-pretty:=[profile?]
			>=dev-haskell/base16-bytestring-1.0:=[profile?]
			dev-haskell/crypton:=[profile?]
			>=dev-haskell/network-run-0.5:=[profile?] <dev-haskell/network-run-0.6:=[profile?]
			dev-haskell/text:=[profile?]
			dev-haskell/unordered-containers:=[profile?]
			dev-haskell/vector:=[profile?]
			dev-haskell/word8:=[profile?] )
"
DEPEND="${RDEPEND}
	>=dev-haskell/cabal-3.4.1.0
	test? ( >=dev-haskell/glob-0.9
		>=dev-haskell/hspec-1.3
		dev-haskell/random
		dev-haskell/typed-process
		!devel? ( >=dev-haskell/aeson-2
				dev-haskell/aeson-pretty
				>=dev-haskell/base16-bytestring-1.0
				dev-haskell/crypton
				>=dev-haskell/network-run-0.5 <dev-haskell/network-run-0.6
				dev-haskell/text
				dev-haskell/unordered-containers
				dev-haskell/vector ) )
"

src_configure() {
	haskell-cabal_src_configure \
		$(cabal_flag devel devel) \
		$(cabal_flag h2spec h2spec)
}
