# Copyright 1999-2022 Gentoo Authors
# Distributed under the terms of the GNU General Public License v2

EAPI=8

# ebuild generated by hackport 0.7.3.0
# CABAL_HACKAGE_REVISION=2

CABAL_FEATURES="lib profile haddock hoogle hscolour"

CABAL_PV="1.0.9-r1"

inherit haskell-cabal

DESCRIPTION="A Setup.hs helper for running doctests"
HOMEPAGE="https://github.com/haskellari/cabal-doctest"
SRC_URI="https://github.com/haskellari/cabal-doctest/archive/refs/tags/v1.0.9-r1.tar.gz"
#S="${WORKDIR}/cabal-doctest-1.0.9-r1"

LICENSE="BSD"
SLOT="0/${PV}"
KEYWORDS="~amd64 ~arm64 ~ppc64 ~x86"

RDEPEND=">=dev-haskell/cabal-1.10:=[profile?]
	>=dev-lang/ghc-8.4.3:=
"
DEPEND="${RDEPEND}
	>=dev-haskell/cabal-2.2.0.1
"
