# Copyright 1999-2026 Gentoo Authors
# Distributed under the terms of the GNU General Public License v2

EAPI=8

# ebuild generated by hackport 0.9.1.0.9999

CABAL_FEATURES="lib profile haddock hoogle hscolour test-suite"
inherit haskell-cabal

DESCRIPTION="Implement gRPC-over-HTTP2 clients"
HOMEPAGE="https://github.com/haskell-grpc-native/http2-grpc-haskell/blob/master/http2-client-grpc/README.md"

LICENSE="BSD"
SLOT="0/${PV}"
KEYWORDS="~amd64"

RDEPEND=">=dev-haskell/async-2.2:=[profile?] <dev-haskell/async-2.3:=[profile?]
	>=dev-haskell/case-insensitive-1.2.0:=[profile?] <dev-haskell/case-insensitive-1.3:=[profile?]
	>=dev-haskell/data-default-class-0.1:=[profile?] <dev-haskell/data-default-class-0.2:=[profile?]
	>=dev-haskell/http2-1.6:=[profile?] <dev-haskell/http2-2.1:=[profile?]
	>=dev-haskell/http2-client-0.9:=[profile?] <dev-haskell/http2-client-0.10:=[profile?]
	>=dev-haskell/http2-grpc-types-0.5:=[profile?] <dev-haskell/http2-grpc-types-0.6:=[profile?]
	>=dev-haskell/lifted-async-0.10:=[profile?] <dev-haskell/lifted-async-0.11:=[profile?]
	>=dev-haskell/lifted-base-0.2:=[profile?] <dev-haskell/lifted-base-0.3:=[profile?]
	>=dev-haskell/text-1.2:=[profile?] <dev-haskell/text-1.3:=[profile?]
	>=dev-haskell/tls-1.4:=[profile?] <dev-haskell/tls-1.6:=[profile?]
	>=dev-lang/ghc-9.0.2:=
"
DEPEND="${RDEPEND}
	>=dev-haskell/cabal-3.4.1.0
"
