# Copyright 1999-2026 Gentoo Authors
# Distributed under the terms of the GNU General Public License v2

EAPI=8

# ebuild generated by hackport 0.9.1.0.9999

CABAL_FEATURES="lib profile haddock hoogle hscolour"
inherit haskell-cabal

DESCRIPTION="A variety of alternative parser combinator libraries"
HOMEPAGE="https://hackage.haskell.org/package/polyparse"

LICENSE=""	# FIXME: license unknown to cabal. Please pick it manually.
SLOT="0/${PV}"
KEYWORDS="~amd64"

RDEPEND=">=dev-lang/ghc-9.0.2:=
	|| ( ( >=dev-haskell/text-1.2.3.0:=[profile?] <dev-haskell/text-1.3:=[profile?] )
		( >=dev-haskell/text-2.0:=[profile?] <dev-haskell/text-3:=[profile?] ) )
"
DEPEND="${RDEPEND}
	>=dev-haskell/cabal-3.4.1.0
"
