# Copyright 1999-2026 Gentoo Authors
# Distributed under the terms of the GNU General Public License v2

EAPI=8

# ebuild generated by hackport 0.9.1.0.9999

CABAL_FEATURES="lib profile haddock hoogle hscolour"
inherit haskell-cabal

DESCRIPTION="Encoders based on 'proto-lens' for gRPC over HTTP2"
HOMEPAGE="https://github.com/haskell-grpc-native/http2-grpc-haskell#readme"

LICENSE="BSD"
SLOT="0/${PV}"
KEYWORDS="~amd64"

RDEPEND=">=dev-haskell/case-insensitive-1.2.0:=[profile?] <dev-haskell/case-insensitive-1.3:=[profile?]
	dev-haskell/http2-grpc-types:=[profile?]
	>=dev-haskell/proto-lens-0.5:=[profile?] <dev-haskell/proto-lens-0.8:=[profile?]
	>=dev-haskell/zlib-0.6.2:=[profile?] <dev-haskell/zlib-0.7:=[profile?]
	>=dev-lang/ghc-9.0.2:=
"
DEPEND="${RDEPEND}
	>=dev-haskell/cabal-3.4.1.0
"
