# Copyright 1999-2026 Gentoo Authors
# Distributed under the terms of the GNU General Public License v2

EAPI=8

# ebuild generated by hackport 0.9.1.0.9999

CABAL_FEATURES="lib profile haddock hoogle hscolour test-suite"
inherit haskell-cabal

DESCRIPTION="A desktop bar similar to xmobar, but with more GUI"
HOMEPAGE="https://github.com/taffybar/taffybar"

LICENSE="BSD"
SLOT="0/${PV}"
KEYWORDS="~amd64"
IUSE="+deprecated-pager-hints +wireplumber"

RDEPEND=">=dev-haskell/aeson-1.4:=[profile?] <dev-haskell/aeson-2.3:=[profile?]
	>=dev-haskell/ansi-terminal-0.10:=[profile?] <dev-haskell/ansi-terminal-1.2:=[profile?]
	>=dev-haskell/attoparsec-0.13:=[profile?] <dev-haskell/attoparsec-0.15:=[profile?]
	>=dev-haskell/conduit-1.3:=[profile?] <dev-haskell/conduit-1.4:=[profile?]
	>=dev-haskell/data-default-0.7:=[profile?] <dev-haskell/data-default-0.9:=[profile?]
	>=dev-haskell/dbus-1.2.11:=[profile?] <dev-haskell/dbus-2:=[profile?]
	>=dev-haskell/dbus-hslogger-0.1.1.1:=[profile?] <dev-haskell/dbus-hslogger-0.2:=[profile?]
	>=dev-haskell/dbus-menu-0.1.3.3:=[profile?] <dev-haskell/dbus-menu-0.2:=[profile?]
	>=dev-haskell/disk-free-space-0.1.0.1:=[profile?] <dev-haskell/disk-free-space-0.2:=[profile?]
	>=dev-haskell/dyre-0.9.0:=[profile?] <dev-haskell/dyre-0.10:=[profile?]
	>=dev-haskell/either-4.0.0.0:=[profile?] <dev-haskell/either-5.1:=[profile?]
	>=dev-haskell/enclosed-exceptions-1.0.0.1:=[profile?] <dev-haskell/enclosed-exceptions-1.1:=[profile?]
	>=dev-haskell/extra-1.7:=[profile?] <dev-haskell/extra-1.9:=[profile?]
	>=dev-haskell/fsnotify-0.4:=[profile?] <dev-haskell/fsnotify-0.5:=[profile?]
	>=dev-haskell/gi-cairo-connector-0.1:=[profile?] <dev-haskell/gi-cairo-connector-0.2:=[profile?]
	>=dev-haskell/gi-cairo-render-0.1:=[profile?] <dev-haskell/gi-cairo-render-0.2:=[profile?]
	>=dev-haskell/gi-gdk3-3.0.30:=[profile?] <dev-haskell/gi-gdk3-3.1:=[profile?]
	>=dev-haskell/gi-gdkpixbuf-2.0.6:=[profile?] <dev-haskell/gi-gdkpixbuf-2.1:=[profile?]
	>=dev-haskell/gi-gdkx113-3.0.17:=[profile?] <dev-haskell/gi-gdkx113-4:=[profile?]
	>=dev-haskell/gi-glib-2.0:=[profile?] <dev-haskell/gi-glib-2.1:=[profile?]
	>=dev-haskell/gi-gobject-2.0:=[profile?] <dev-haskell/gi-gobject-2.1:=[profile?]
	>=dev-haskell/gi-gtk-hs-0.3.17:=[profile?] <dev-haskell/gi-gtk-hs-0.4:=[profile?]
	>=dev-haskell/gi-gtk-layer-shell-0.1.7:=[profile?] <dev-haskell/gi-gtk-layer-shell-0.2:=[profile?]
	>=dev-haskell/gi-gtk3-3.0.44:=[profile?] <dev-haskell/gi-gtk3-4:=[profile?]
	>=dev-haskell/gi-pango-1.0:=[profile?] <dev-haskell/gi-pango-1.1:=[profile?]
	>=dev-haskell/gtk-scaling-image-0.1.0.1:=[profile?] <dev-haskell/gtk-scaling-image-0.2:=[profile?]
	>=dev-haskell/gtk-sni-tray-0.2.1.2:=[profile?] <dev-haskell/gtk-sni-tray-0.3:=[profile?]
	>=dev-haskell/gtk-strut-0.1.4.1:=[profile?] <dev-haskell/gtk-strut-0.2:=[profile?]
	>=dev-haskell/haskell-gi-base-0.24:=[profile?] <dev-haskell/haskell-gi-base-0.27:=[profile?]
	>=dev-haskell/hslogger-1.2:=[profile?] <dev-haskell/hslogger-1.4:=[profile?]
	>=dev-haskell/hspec-2.8:=[profile?] <dev-haskell/hspec-3:=[profile?]
	>=dev-haskell/hstringtemplate-0.8:=[profile?] <dev-haskell/hstringtemplate-0.9:=[profile?]
	>=dev-haskell/http-client-0.5:=[profile?] <dev-haskell/http-client-0.8:=[profile?]
	>=dev-haskell/http-client-tls-0.3:=[profile?] <dev-haskell/http-client-tls-0.4:=[profile?]
	>=dev-haskell/http-conduit-2.3:=[profile?] <dev-haskell/http-conduit-2.4:=[profile?]
	>=dev-haskell/http-types-0.12:=[profile?] <dev-haskell/http-types-0.13:=[profile?]
	>=dev-haskell/juicypixels-3.3:=[profile?] <dev-haskell/juicypixels-3.4:=[profile?]
	>=dev-haskell/monad-control-1.0:=[profile?] <dev-haskell/monad-control-1.1:=[profile?]
	>=dev-haskell/multimap-1.2.1:=[profile?] <dev-haskell/multimap-1.3:=[profile?]
	>=dev-haskell/network-3.1:=[profile?] <dev-haskell/network-3.3:=[profile?]
	>=dev-haskell/optparse-applicative-0.17:=[profile?] <dev-haskell/optparse-applicative-0.20:=[profile?]
	>=dev-haskell/parsec-3.1:=[profile?] <dev-haskell/parsec-3.2:=[profile?]
	>=dev-haskell/quickcheck-2:=[profile?] <dev-haskell/quickcheck-2.17:=[profile?]
	>=dev-haskell/rate-limit-1.1.1:=[profile?] <dev-haskell/rate-limit-1.5:=[profile?]
	>=dev-haskell/regex-compat-0.95:=[profile?] <dev-haskell/regex-compat-0.96:=[profile?]
	>=dev-haskell/safe-0.3:=[profile?] <dev-haskell/safe-1:=[profile?]
	>=dev-haskell/scotty-0.20:=[profile?] <dev-haskell/scotty-0.31:=[profile?]
	>=dev-haskell/split-0.1.4.2:=[profile?] <dev-haskell/split-0.3:=[profile?]
	>=dev-haskell/status-notifier-item-0.3.2.14:=[profile?] <dev-haskell/status-notifier-item-0.4:=[profile?]
	>=dev-haskell/text-1.2:=[profile?] <dev-haskell/text-2.2:=[profile?]
	>=dev-haskell/time-locale-compat-0.1:=[profile?] <dev-haskell/time-locale-compat-0.2:=[profile?]
	>=dev-haskell/time-units-1.0.0:=[profile?] <dev-haskell/time-units-1.1:=[profile?]
	>=dev-haskell/tuple-0.3.0.2:=[profile?] <dev-haskell/tuple-0.4:=[profile?]
	>=dev-haskell/typed-process-0.2:=[profile?] <dev-haskell/typed-process-0.3:=[profile?]
	>=dev-haskell/unliftio-0.2:=[profile?] <dev-haskell/unliftio-0.3:=[profile?]
	>=dev-haskell/unliftio-core-0.2:=[profile?] <dev-haskell/unliftio-core-0.3:=[profile?]
	>=dev-haskell/utf8-string-1.0:=[profile?] <dev-haskell/utf8-string-1.1:=[profile?]
	>=dev-haskell/x11-1.5.0.1:=[profile?] <dev-haskell/x11-1.11:=[profile?]
	>=dev-haskell/xdg-basedir-0.2:=[profile?] <dev-haskell/xdg-basedir-0.3:=[profile?]
	>=dev-haskell/xdg-desktop-entry-0.1.1.5:=[profile?] <dev-haskell/xdg-desktop-entry-0.2:=[profile?]
	>=dev-haskell/xml-1.3:=[profile?] <dev-haskell/xml-1.4:=[profile?]
	>=dev-haskell/xml-helpers-1.0:=[profile?] <dev-haskell/xml-helpers-1.1:=[profile?]
	>=dev-haskell/xmonad-0.17:=[profile?] <dev-haskell/xmonad-0.19:=[profile?]
	>=dev-haskell/xmonad-contrib-0.17:=[profile?] <dev-haskell/xmonad-contrib-0.19:=[profile?]
	>=dev-haskell/yaml-0.11:=[profile?] <dev-haskell/yaml-0.12:=[profile?]
	>=dev-lang/dhall-1.40:=[profile?] <dev-lang/dhall-1.43:=[profile?]
	>=dev-lang/ghc-9.0.2:=
	unknown-pkg-config/libudev
	x11-libs/gtk+:3
	wireplumber? ( >=dev-haskell/gi-wireplumber-0.5.14.2:=[profile?] <dev-haskell/gi-wireplumber-0.6:=[profile?] )
"
DEPEND="${RDEPEND}
	>=dev-haskell/cabal-3.4.1.0
	virtual/pkgconfig
	test? ( dev-haskell/hspec-core
		dev-haskell/hspec-golden )
"

src_configure() {
	haskell-cabal_src_configure \
		$(cabal_flag deprecated-pager-hints deprecated-pager-hints) \
		$(cabal_flag wireplumber wireplumber)
}
