# Copyright 1999-2026 Gentoo Authors
# Distributed under the terms of the GNU General Public License v2

EAPI=8

# ebuild generated by hackport 0.9.1.0.9999

CABAL_FEATURES="lib profile haddock hoogle hscolour test-suite"
inherit haskell-cabal

DESCRIPTION="A desktop bar similar to xmobar, but with more GUI"
HOMEPAGE="https://github.com/taffybar/taffybar"

LICENSE="BSD"
SLOT="0/${PV}"
KEYWORDS="~amd64"
IUSE="+deprecated-pager-hints"

RDEPEND="dev-haskell/aeson:=[profile?]
	dev-haskell/ansi-terminal:=[profile?]
	dev-haskell/attoparsec:=[profile?]
	dev-haskell/conduit:=[profile?]
	dev-haskell/data-default:=[profile?]
	>=dev-haskell/dbus-1.2.11:=[profile?] <dev-haskell/dbus-2.0.0:=[profile?]
	>=dev-haskell/dbus-hslogger-0.1.1.0:=[profile?] <dev-haskell/dbus-hslogger-0.2.0.0:=[profile?]
	>=dev-haskell/dbus-menu-0.1.3.2:=[profile?]
	>=dev-haskell/disk-free-space-0.1.0.1:=[profile?]
	>=dev-haskell/dyre-0.9.0:=[profile?] <dev-haskell/dyre-0.10:=[profile?]
	>=dev-haskell/either-4.0.0.0:=[profile?]
	>=dev-haskell/enclosed-exceptions-1.0.0.1:=[profile?]
	dev-haskell/extra:=[profile?]
	>=dev-haskell/fsnotify-0.4:=[profile?] <dev-haskell/fsnotify-0.5:=[profile?]
	dev-haskell/gi-cairo-connector:=[profile?]
	dev-haskell/gi-cairo-render:=[profile?]
	>=dev-haskell/gi-gdk3-3.0.30:=[profile?] <dev-haskell/gi-gdk3-3.1:=[profile?]
	>=dev-haskell/gi-gdkpixbuf-2.0.6:=[profile?] <dev-haskell/gi-gdkpixbuf-2.1:=[profile?]
	>=dev-haskell/gi-gdkx113-3.0.17:=[profile?] <dev-haskell/gi-gdkx113-4:=[profile?]
	dev-haskell/gi-glib:=[profile?]
	>=dev-haskell/gi-gtk-hs-0.3.17:=[profile?] <dev-haskell/gi-gtk-hs-0.4:=[profile?]
	>=dev-haskell/gi-gtk-layer-shell-0.1.7:=[profile?]
	>=dev-haskell/gi-gtk3-3.0.44:=[profile?] <dev-haskell/gi-gtk3-4:=[profile?]
	dev-haskell/gi-pango:=[profile?]
	>=dev-haskell/gtk-scaling-image-0.1.0.0:=[profile?] <dev-haskell/gtk-scaling-image-0.2:=[profile?]
	>=dev-haskell/gtk-sni-tray-0.2.1.0:=[profile?]
	>=dev-haskell/gtk-strut-0.1.4.0:=[profile?]
	>=dev-haskell/haskell-gi-base-0.24:=[profile?]
	dev-haskell/hslogger:=[profile?]
	dev-haskell/hspec:=[profile?]
	>=dev-haskell/hstringtemplate-0.8:=[profile?] <dev-haskell/hstringtemplate-0.9:=[profile?]
	>=dev-haskell/http-client-0.5:=[profile?]
	dev-haskell/http-client-tls:=[profile?]
	dev-haskell/http-conduit:=[profile?]
	dev-haskell/http-types:=[profile?]
	dev-haskell/juicypixels:=[profile?]
	dev-haskell/monad-control:=[profile?]
	>=dev-haskell/multimap-1.2.1:=[profile?]
	dev-haskell/network:=[profile?]
	dev-haskell/optparse-applicative:=[profile?]
	>=dev-haskell/parsec-3.1:=[profile?]
	>=dev-haskell/quickcheck-2:=[profile?]
	>=dev-haskell/rate-limit-1.1.1:=[profile?]
	dev-haskell/regex-compat:=[profile?]
	>=dev-haskell/safe-0.3:=[profile?] <dev-haskell/safe-1:=[profile?]
	>=dev-haskell/scotty-0.20:=[profile?] <dev-haskell/scotty-0.31:=[profile?]
	>=dev-haskell/split-0.1.4.2:=[profile?]
	>=dev-haskell/status-notifier-item-0.3.2.11:=[profile?]
	dev-haskell/text:=[profile?]
	>=dev-haskell/time-locale-compat-0.1:=[profile?] <dev-haskell/time-locale-compat-0.2:=[profile?]
	>=dev-haskell/time-units-1.0.0:=[profile?]
	>=dev-haskell/tuple-0.3.0.2:=[profile?]
	dev-haskell/typed-process:=[profile?]
	dev-haskell/unliftio:=[profile?]
	dev-haskell/unliftio-core:=[profile?]
	dev-haskell/utf8-string:=[profile?]
	>=dev-haskell/x11-1.5.0.1:=[profile?]
	>=dev-haskell/xdg-basedir-0.2:=[profile?] <dev-haskell/xdg-basedir-0.3:=[profile?]
	>=dev-haskell/xdg-desktop-entry-0.1.1.4:=[profile?]
	dev-haskell/xml:=[profile?]
	dev-haskell/xml-helpers:=[profile?]
	x11-wm/xmonad:=[profile?]
	x11-wm/xmonad-contrib:=[profile?]
	dev-haskell/yaml:=[profile?]
	dev-lang/dhall:=[profile?]
	>=dev-lang/ghc-9.0.2:=
	x11-libs/gtk+:3
"
DEPEND="${RDEPEND}
	>=dev-haskell/cabal-3.4.1.0
	virtual/pkgconfig
	test? ( dev-haskell/hspec-core
		dev-haskell/hspec-golden )
"

src_configure() {
	haskell-cabal_src_configure \
		$(cabal_flag deprecated-pager-hints deprecated-pager-hints)
}
