# Copyright 1999-2026 Gentoo Authors
# Distributed under the terms of the GNU General Public License v2

EAPI=8

# ebuild generated by hackport 0.9.1.0.9999

CABAL_FEATURES="lib profile haddock hoogle hscolour test-suite"
inherit haskell-cabal

DESCRIPTION="A Polysemy effect for time"
HOMEPAGE="https://github.com/tek/polysemy-time#readme"

LICENSE=""	# FIXME: license unknown to cabal. Please pick it manually.
SLOT="0/${PV}"
KEYWORDS="~amd64 ~x86"

RDEPEND=">=dev-haskell/aeson-2.1.2.1:=[profile?] <dev-haskell/aeson-2.3:=[profile?]
	>=dev-haskell/incipit-core-0.4.1.0:=[profile?] <dev-haskell/incipit-core-0.7:=[profile?]
	>=dev-haskell/torsor-0.1:=[profile?] <dev-haskell/torsor-0.2:=[profile?]
	>=dev-lang/ghc-9.4.8:=
"
DEPEND="${RDEPEND}
	>=dev-haskell/cabal-3.8.1.0
	test? ( >=dev-haskell/polysemy-test-0.3.1.6 <dev-haskell/polysemy-test-0.11
		>=dev-haskell/tasty-1.4.2 <dev-haskell/tasty-1.6 )
"
