# Copyright 1999-2026 Gentoo Authors
# Distributed under the terms of the GNU General Public License v2

EAPI=8

# ebuild generated by hackport 0.9.1.0.9999

CABAL_FEATURES="lib profile haddock hoogle hscolour"
inherit haskell-cabal

DESCRIPTION="Protocol buffer compiler for the proto-lens library"
HOMEPAGE="https://github.com/google/proto-lens#readme"

LICENSE="BSD"
SLOT="0/${PV}"
KEYWORDS="~amd64"

CABAL_CHDEPS=(
  'base >=4.10 && <4.21' 'base >=4.10 && <5'
  'ghc >=8.2 && <9.11' 'ghc >=8.2 && <9.15'
)

RDEPEND=">=dev-haskell/ghc-paths-0.1:=[profile?] <dev-haskell/ghc-paths-0.3:=[profile?]
	>=dev-haskell/ghc-source-gen-0.4:=[profile?] <dev-haskell/ghc-source-gen-0.6:=[profile?]
	>=dev-haskell/lens-family-1.2:=[profile?] <dev-haskell/lens-family-2.2:=[profile?]
	>=dev-haskell/proto-lens-0.7:=[profile?] <dev-haskell/proto-lens-0.10:=[profile?]
	>=dev-haskell/proto-lens-runtime-0.7:=[profile?] <dev-haskell/proto-lens-runtime-0.10:=[profile?]
	>=dev-haskell/text-1.2:=[profile?] <dev-haskell/text-2.5:=[profile?]
	>=dev-lang/ghc-8.2:=[profile?] <dev-lang/ghc-9.15:=[profile?]
	>=dev-lang/ghc-9.0.2:=
"
DEPEND="${RDEPEND}
	>=dev-haskell/cabal-3.4.1.0
"
