# Copyright 1999-2024 Gentoo Authors
# Distributed under the terms of the GNU General Public License v2

EAPI=8

# ebuild generated by hackport 0.8.4.0.9999

CABAL_FEATURES="lib profile haddock hoogle hscolour"
inherit haskell-cabal

DESCRIPTION="Protocol buffer compiler for the proto-lens library"
HOMEPAGE="https://github.com/google/proto-lens#readme"

LICENSE="BSD"
SLOT="0/${PV}"
KEYWORDS="~amd64"

RDEPEND=">=dev-haskell/ghc-paths-0.1:=[profile?] <dev-haskell/ghc-paths-0.2:=[profile?]
	>=dev-haskell/ghc-source-gen-0.4:=[profile?] <dev-haskell/ghc-source-gen-0.5:=[profile?]
	>=dev-haskell/lens-family-1.2:=[profile?] <dev-haskell/lens-family-2.2:=[profile?]
	>=dev-haskell/proto-lens-0.7:=[profile?] <dev-haskell/proto-lens-0.8:=[profile?]
	>=dev-haskell/proto-lens-runtime-0.7:=[profile?] <dev-haskell/proto-lens-runtime-0.8:=[profile?]
	>=dev-haskell/text-1.2:=[profile?] <dev-haskell/text-2.2:=[profile?]
"
DEPEND="${RDEPEND}
	>=dev-haskell/cabal-3.2.1.0
"
