# Copyright 1999-2024 Gentoo Authors
# Distributed under the terms of the GNU General Public License v2

EAPI=8

# ebuild generated by hackport 0.8.5.1.9999

CABAL_HACKAGE_REVISION=6

CABAL_FEATURES="lib profile haddock hoogle hscolour test-suite"
inherit haskell-cabal

DESCRIPTION="multipart/form-data (e.g file upload) support for servant"
HOMEPAGE="https://github.com/haskell-servant/servant-multipart#readme"

LICENSE="BSD"
SLOT="0/${PV}"
KEYWORDS="~amd64"

RDEPEND=">=dev-haskell/lens-4.17:=[profile?] <dev-haskell/lens-5.3:=[profile?]
	>=dev-haskell/resourcet-1.2.2:=[profile?] <dev-haskell/resourcet-1.4:=[profile?]
	>=dev-haskell/servant-0.16:=[profile?] <dev-haskell/servant-0.21:=[profile?]
	>=dev-haskell/servant-docs-0.10:=[profile?] <dev-haskell/servant-docs-0.14:=[profile?]
	>=dev-haskell/servant-foreign-0.15:=[profile?] <dev-haskell/servant-foreign-0.17:=[profile?]
	>=dev-haskell/servant-multipart-api-0.12:=[profile?] <dev-haskell/servant-multipart-api-0.13:=[profile?]
	>=dev-haskell/servant-server-0.16:=[profile?] <dev-haskell/servant-server-0.21:=[profile?]
	>=dev-haskell/string-conversions-0.4.0.1:=[profile?] <dev-haskell/string-conversions-0.5:=[profile?]
	>=dev-haskell/text-1.2.3.0:=[profile?] <dev-haskell/text-2.2:=[profile?]
	>=dev-haskell/wai-3.2.1.2:=[profile?] <dev-haskell/wai-3.3:=[profile?]
	>=dev-haskell/wai-extra-3.0.24.3:=[profile?] <dev-haskell/wai-extra-3.2:=[profile?]
	>=dev-lang/ghc-9.0.2:=
"
DEPEND="${RDEPEND}
	>=dev-haskell/cabal-3.4.1.0
	test? ( dev-haskell/http-types
		dev-haskell/tasty
		dev-haskell/tasty-wai )
"
