# Copyright 1999-2026 Gentoo Authors
# Distributed under the terms of the GNU General Public License v2

EAPI=8

# ebuild generated by hackport 0.9.1.0.9999

CABAL_FEATURES="lib profile haddock hoogle hscolour"
inherit haskell-cabal

DESCRIPTION="Library for creating strut windows with gi-gtk"
HOMEPAGE="https://github.com/taffybar/gtk-strut#readme"

LICENSE="BSD"
SLOT="0/${PV}"
KEYWORDS="~amd64"

RDEPEND=">=dev-haskell/data-default-0.7:=[profile?] <dev-haskell/data-default-0.9:=[profile?]
	>=dev-haskell/gi-gdk3-3.0:=[profile?] <dev-haskell/gi-gdk3-3.1:=[profile?]
	>=dev-haskell/gi-gtk3-3.0:=[profile?] <dev-haskell/gi-gtk3-3.1:=[profile?]
	>=dev-haskell/hslogger-1.2:=[profile?] <dev-haskell/hslogger-1.4:=[profile?]
	>=dev-haskell/text-1.2:=[profile?] <dev-haskell/text-2.2:=[profile?]
	>=dev-lang/ghc-9.0.2:=
"
DEPEND="${RDEPEND}
	>=dev-haskell/cabal-3.4.1.0
"
