# Copyright 1999-2026 Gentoo Authors
# Distributed under the terms of the GNU General Public License v2

EAPI=8

# ebuild generated by hackport 0.9.1.0.9999

CABAL_FEATURES="lib profile haddock hoogle hscolour"
inherit haskell-cabal

DESCRIPTION="Handle per-operating-system X.509 accessors and storage"
HOMEPAGE="https://github.com/kazu-yamamoto/crypton-certificate"

LICENSE="BSD"
SLOT="0/${PV}"
KEYWORDS="~amd64"

RDEPEND=">=dev-haskell/crypton-pem-0.2.4:=[profile?] <dev-haskell/crypton-pem-0.4:=[profile?]
	>=dev-haskell/crypton-x509-1.9.0:=[profile?] <dev-haskell/crypton-x509-1.10:=[profile?]
	>=dev-haskell/crypton-x509-store-1.9.0:=[profile?] <dev-haskell/crypton-x509-store-1.10:=[profile?]
	>=dev-lang/ghc-9.0.2:=
"
DEPEND="${RDEPEND}
	>=dev-haskell/cabal-3.4.1.0
"
