# Copyright 1999-2026 Gentoo Authors
# Distributed under the terms of the GNU General Public License v2

EAPI=8

# ebuild generated by hackport 0.9.1.0.9999

CABAL_FEATURES="lib profile haddock hoogle hscolour test-suite"
inherit haskell-cabal

DESCRIPTION="Space-efficient bit vectors"
HOMEPAGE="https://github.com/Bodigrim/bitvec"

LICENSE="BSD"
SLOT="0/${PV}"
KEYWORDS="~amd64"
IUSE="+simd"

RDEPEND=">=dev-haskell/primitive-0.5:=[profile?] <dev-haskell/primitive-0.10:=[profile?]
	>=dev-haskell/vector-0.13:=[profile?] <dev-haskell/vector-0.14:=[profile?]
	>=dev-lang/ghc-9.0.2:=
"
DEPEND="${RDEPEND}
	>=dev-haskell/cabal-3.4.1.0
	test? ( >=dev-haskell/quickcheck-classes-0.6.1 <dev-haskell/quickcheck-classes-0.7
		<dev-haskell/quickcheck-classes-base-0.7
		<dev-haskell/tasty-1.6
		<dev-haskell/tasty-quickcheck-0.12 )
"

src_configure() {
	haskell-cabal_src_configure \
		$(cabal_flag simd simd)
}
