# Copyright 1999-2026 Gentoo Authors
# Distributed under the terms of the GNU General Public License v2

EAPI=8

# ebuild generated by hackport 0.9.1.0.9999

CABAL_FEATURES="lib profile haddock hoogle hscolour test-suite"
inherit haskell-cabal

DESCRIPTION="Module-Lattice-based Key-Encapsulation Mechanism"
HOMEPAGE="https://codeberg.org/ocheron/hs-mlkem#readme"

LICENSE="BSD"
SLOT="0/${PV}"
KEYWORDS="~amd64"
IUSE="+crypton"

RDEPEND=">=dev-haskell/primitive-0.7.2:=[profile?]
	>=dev-lang/ghc-9.0.2:=
	crypton? ( >=dev-haskell/crypton-1.1.1:=[profile?]
			dev-haskell/ram:=[profile?] )
	!crypton? ( >=dev-haskell/cryptonite-0.26:=[profile?]
			dev-haskell/memory:=[profile?] )
"
DEPEND="${RDEPEND}
	>=dev-haskell/cabal-3.4.1.0
	test? ( dev-haskell/aeson
		dev-haskell/tasty
		dev-haskell/tasty-hunit
		dev-haskell/tasty-quickcheck
		dev-haskell/text
		dev-haskell/zlib )
"

src_configure() {
	haskell-cabal_src_configure \
		$(cabal_flag crypton use_crypton)
}
