# Copyright 1999-2024 Gentoo Authors
# Distributed under the terms of the GNU General Public License v2

EAPI=8

# ebuild generated by hackport 0.8.5.1.9999

CABAL_FEATURES="lib profile haddock hoogle hscolour"
inherit haskell-cabal

DESCRIPTION="Law-abiding optics for aeson"
HOMEPAGE="https://github.com/phadej/aeson-optics"

LICENSE="MIT"
SLOT="0/${PV}"
KEYWORDS="~amd64"

CABAL_CHDEPS=(
	'text          >=1.2.2.0  && <1.3 || >=2.0 && <2.1' 'text >=2.0 && <2.2'
)

RDEPEND=">=dev-haskell/aeson-2.0.3.0:=[profile?] <dev-haskell/aeson-2.3:=[profile?]
	>=dev-haskell/optics-core-0.4.1:=[profile?] <dev-haskell/optics-core-0.5:=[profile?]
	>=dev-haskell/optics-extra-0.4.1:=[profile?] <dev-haskell/optics-extra-0.5:=[profile?]
	>=dev-haskell/scientific-0.3.4.9:=[profile?] <dev-haskell/scientific-0.4:=[profile?]
	>=dev-haskell/text-short-0.1.5:=[profile?] <dev-haskell/text-short-0.2:=[profile?]
	>=dev-haskell/vector-0.11:=[profile?] <dev-haskell/vector-0.14:=[profile?]
	>=dev-lang/ghc-9.0.2:=
	>=dev-haskell/text-2.0:=[profile?] <dev-haskell/text-2.2:=[profile?]
"
DEPEND="${RDEPEND}
	>=dev-haskell/cabal-3.4.1.0
"
