# Copyright 1999-2026 Gentoo Authors
# Distributed under the terms of the GNU General Public License v2

EAPI=8

# ebuild generated by hackport 0.9.1.0.9999

CABAL_FEATURES="lib profile haddock hoogle hscolour"
inherit haskell-cabal

DESCRIPTION="Generic GTK image scaling helpers for haskell-gi"
HOMEPAGE="https://github.com/taffybar/gtk-scaling-image#readme"

LICENSE="BSD"
SLOT="0/${PV}"
KEYWORDS="~amd64"

RDEPEND=">=dev-haskell/gi-cairo-connector-0.1:=[profile?] <dev-haskell/gi-cairo-connector-0.2:=[profile?]
	>=dev-haskell/gi-cairo-render-0.1:=[profile?] <dev-haskell/gi-cairo-render-0.2:=[profile?]
	>=dev-haskell/gi-gdk3-3.0:=[profile?] <dev-haskell/gi-gdk3-3.1:=[profile?]
	>=dev-haskell/gi-gdkpixbuf-2.0.16:=[profile?] <dev-haskell/gi-gdkpixbuf-2.1:=[profile?]
	>=dev-haskell/gi-gtk3-3.0:=[profile?] <dev-haskell/gi-gtk3-3.1:=[profile?]
	>=dev-haskell/hslogger-1.2:=[profile?] <dev-haskell/hslogger-1.4:=[profile?]
	>=dev-lang/ghc-9.0.2:=
"
DEPEND="${RDEPEND}
	>=dev-haskell/cabal-3.4.1.0
"
