# Copyright 1999-2026 Gentoo Authors
# Distributed under the terms of the GNU General Public License v2

EAPI=8

# ebuild generated by hackport 0.9.1.0.9999
#hackport: flags: -hans

CABAL_FEATURES="lib profile haddock hoogle hscolour test-suite"
inherit haskell-cabal

DESCRIPTION="TLS protocol native implementation"
HOMEPAGE="https://github.com/haskell-tls/hs-tls"

LICENSE="BSD"
SLOT="0/${PV}"
KEYWORDS="~amd64"
IUSE="devel"

RDEPEND="dev-haskell/base16-bytestring:=[profile?]
	>=dev-haskell/cereal-0.5.3:=[profile?] <dev-haskell/cereal-0.6:=[profile?]
	>=dev-haskell/crypton-1.1.0:=[profile?] <dev-haskell/crypton-1.2:=[profile?]
	>=dev-haskell/crypton-asn1-encoding-0.10.0:=[profile?] <dev-haskell/crypton-asn1-encoding-0.11:=[profile?]
	>=dev-haskell/crypton-asn1-types-0.4.1:=[profile?] <dev-haskell/crypton-asn1-types-0.5:=[profile?]
	>=dev-haskell/crypton-x509-1.9:=[profile?] <dev-haskell/crypton-x509-1.10:=[profile?]
	>=dev-haskell/crypton-x509-store-1.9:=[profile?] <dev-haskell/crypton-x509-store-1.10:=[profile?]
	>=dev-haskell/crypton-x509-validation-1.9:=[profile?] <dev-haskell/crypton-x509-validation-1.10:=[profile?]
	dev-haskell/data-default:=[profile?]
	dev-haskell/ech-config:=[profile?]
	>=dev-haskell/hpke-0.1.0:=[profile?] <dev-haskell/hpke-0.2:=[profile?]
	>=dev-haskell/network-3.1:=[profile?]
	dev-haskell/ram:=[profile?]
	>=dev-haskell/random-1.2:=[profile?] <dev-haskell/random-1.4:=[profile?]
	>=dev-haskell/serialise-0.2:=[profile?] <dev-haskell/serialise-0.3:=[profile?]
	>=dev-haskell/unix-time-0.4.11:=[profile?] <dev-haskell/unix-time-0.5:=[profile?]
	>=dev-haskell/zlib-0.7:=[profile?] <dev-haskell/zlib-0.8:=[profile?]
	>=dev-lang/ghc-9.0.2:=
	devel? ( dev-haskell/crypton-x509-system:=[profile?]
			>=dev-haskell/network-run-0.5:=[profile?] )
"
DEPEND="${RDEPEND}
	>=dev-haskell/cabal-3.4.1.0
	test? ( dev-haskell/async
		dev-haskell/base64-bytestring
		dev-haskell/hspec
		dev-haskell/quickcheck
		dev-haskell/time-hourglass )
"

src_configure() {
	haskell-cabal_src_configure \
		$(cabal_flag devel devel) \
		--flag=-hans
}
