# Copyright 1999-2026 Gentoo Authors
# Distributed under the terms of the GNU General Public License v2

EAPI=8

# ebuild generated by hackport 0.9.1.0.9999

CABAL_FEATURES="lib profile haddock hoogle hscolour test-suite"
inherit haskell-cabal

DESCRIPTION="Parse files conforming to the xdg desktop entry spec"
HOMEPAGE="https://github.com/taffybar/taffybar/tree/master/packages/xdg-desktop-entry"

LICENSE="BSD"
SLOT="0/${PV}"
KEYWORDS="~amd64"

RDEPEND=">=dev-haskell/either-5.0.1.1:=[profile?] <dev-haskell/either-5.1:=[profile?]
	>=dev-haskell/ini-0.4.1:=[profile?] <dev-haskell/ini-0.6:=[profile?]
	>=dev-haskell/multimap-1.2.1:=[profile?] <dev-haskell/multimap-1.3:=[profile?]
	>=dev-haskell/safe-0.3.19:=[profile?] <dev-haskell/safe-0.4:=[profile?]
	>=dev-haskell/text-1.2.4:=[profile?] <dev-haskell/text-2.2:=[profile?]
	>=dev-haskell/unordered-containers-0.2.10:=[profile?] <dev-haskell/unordered-containers-0.3:=[profile?]
	>=dev-lang/ghc-9.0.2:=
"
DEPEND="${RDEPEND}
	>=dev-haskell/cabal-3.4.1.0
	test? ( dev-haskell/hspec
		dev-haskell/temporary )
"
