# Copyright 1999-2026 Gentoo Authors
# Distributed under the terms of the GNU General Public License v2

EAPI=8

# ebuild generated by hackport 0.9.1.0.9999

CABAL_FEATURES="lib profile haddock hoogle hscolour test-suite"
inherit haskell-cabal

DESCRIPTION="A standalone StatusNotifierItem/AppIndicator tray"
HOMEPAGE="https://github.com/taffybar/gtk-sni-tray#readme"

LICENSE="BSD"
SLOT="0/${PV}"
KEYWORDS="~amd64"

RDEPEND=">=dev-haskell/dbus-1:=[profile?] <dev-haskell/dbus-2:=[profile?]
	>=dev-haskell/dbus-hslogger-0.1.1.1:=[profile?] <dev-haskell/dbus-hslogger-0.2:=[profile?]
	>=dev-haskell/dbus-menu-0.1.3.3:=[profile?] <dev-haskell/dbus-menu-0.2:=[profile?]
	>=dev-haskell/enclosed-exceptions-1.0.0.1:=[profile?] <dev-haskell/enclosed-exceptions-1.1:=[profile?]
	>=dev-haskell/gi-cairo-1.0:=[profile?] <dev-haskell/gi-cairo-1.1:=[profile?]
	>=dev-haskell/gi-cairo-connector-0.1:=[profile?] <dev-haskell/gi-cairo-connector-0.2:=[profile?]
	>=dev-haskell/gi-cairo-render-0.1:=[profile?] <dev-haskell/gi-cairo-render-0.2:=[profile?]
	>=dev-haskell/gi-dbusmenugtk3-0.4:=[profile?] <dev-haskell/gi-dbusmenugtk3-0.5:=[profile?]
	>=dev-haskell/gi-gdk3-3.0:=[profile?] <dev-haskell/gi-gdk3-3.1:=[profile?]
	>=dev-haskell/gi-gdkpixbuf-2.0.16:=[profile?] <dev-haskell/gi-gdkpixbuf-2.1:=[profile?]
	>=dev-haskell/gi-glib-2.0:=[profile?] <dev-haskell/gi-glib-2.1:=[profile?]
	>=dev-haskell/gi-gobject-2.0:=[profile?] <dev-haskell/gi-gobject-2.1:=[profile?]
	>=dev-haskell/gi-gtk-layer-shell-0.1:=[profile?] <dev-haskell/gi-gtk-layer-shell-0.2:=[profile?]
	>=dev-haskell/gi-gtk3-3.0:=[profile?] <dev-haskell/gi-gtk3-3.1:=[profile?]
	>=dev-haskell/gtk-scaling-image-0.1.0.1:=[profile?] <dev-haskell/gtk-scaling-image-0.2:=[profile?]
	>=dev-haskell/gtk-strut-0.1.4.1:=[profile?] <dev-haskell/gtk-strut-0.2:=[profile?]
	>=dev-haskell/haskell-gi-0.21.2:=[profile?] <dev-haskell/haskell-gi-0.27:=[profile?]
	>=dev-haskell/haskell-gi-base-0.21.1:=[profile?] <dev-haskell/haskell-gi-base-0.27:=[profile?]
	>=dev-haskell/hslogger-1.2:=[profile?] <dev-haskell/hslogger-1.4:=[profile?]
	>=dev-haskell/optparse-applicative-0.14:=[profile?] <dev-haskell/optparse-applicative-0.20:=[profile?]
	>=dev-haskell/status-notifier-item-0.3.2.14:=[profile?] <dev-haskell/status-notifier-item-0.4:=[profile?]
	>=dev-haskell/text-1.2:=[profile?] <dev-haskell/text-2.2:=[profile?]
	>=dev-haskell/transformers-base-0.4:=[profile?] <dev-haskell/transformers-base-0.5:=[profile?]
	>=dev-lang/ghc-9.0.2:=
	x11-libs/gtk+:3
"
DEPEND="${RDEPEND}
	>=dev-haskell/cabal-3.4.1.0
	virtual/pkgconfig
	test? ( <dev-haskell/hspec-3 )
"
